Repository you06/cherry-pick-playground, pull requests merged in 2019-07, with the labels that each got.

#24 add hotfix7
  hotfix7.go
Labels: needs-cherry-pick-1.0

#27 add hotfix 8
  hotfix8.go
Labels: needs-cherry-pick-1.0

#30 add hotfix 9
  hotfix9.go
Labels: needs-cherry-pick-1.0

#34 add hotfix11
  hotfix
  hotfix11
  hotfix11.go
Labels: needs-cherry-pick-1.0

#36 Update README.md
  README.md
Labels: needs-cherry-pick-1.0

#50 add hotfix24
  hotfix24.go
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.5

#22 add hotfix6
  hotfix6.go
Labels: bug, documentation, enhancement

#40 add hotfix13
  hotfix13.go
Labels: can merge

#55 add hotfix25
  hotfix25.go
Labels: can merge

#46 add hotfix20
  hotfix20.go
Labels: can merge

#49 add hotfix23
  hotfix23.go
Labels: bug, can merge

#48 add hotfix22
  hotfix22.go
Labels: can merge

#56 add hotfix26
  hotfix26.go
Labels: can merge
