Repository you06/cherry-pick-playground, pull requests merged in 2019-08, with the labels that each got.

#61 add hotfix30
  hotfix30.go
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.5

#69 add hotfix31
  hotfix31.go
Labels: can merge

#60 add hotfix29
  hotfix29.go
Labels: can merge

#51 add hotfix24 (#50)
  hotfix24.go
Labels: can merge, status/PTAL, status/ReqChange, type/1.5 cherry-pick

#57 Update test.js
  test.js
Labels: can merge
